helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-home
    forcestring: true
  - name: image.tag
    value: main@sha256:34650d1d85ede74f8b375d4b7a0454426bf3d73024e8e3424e86cb3cf997f4b9
    forcestring: true
