helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-home
    forcestring: true
  - name: image.tag
    value: main@sha256:a288b36d3609a5195abd3dc9b4a315f67462af968034b7cef51f6877860c8621
    forcestring: true
