helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-home
    forcestring: true
  - name: image.tag
    value: main@sha256:7b3cd257a7f3449079a99e8cfbebb324fdb5710ca7b3015b6103372ec0175c15
    forcestring: true
